services:

  ExampleApp:
    class: processor.ExampleApp
    arguments: [$Mongodb]

  Mongodb:
    class: utilities.my_mongo.Mongodb
    arguments: ['%mongo_db%', '%mongo_col%', '%mongo_host%', '%mongo_port%']

chains:
  - ExampleApp