services:
  ExampleApp:
    class: processor.ExampleApp
    arguments: ~

  RabbitMqConsumer:
    class: chains.rabbitmq_consumer.RabbitMqConsumer
    arguments:
      queue_config: '%queue%'
      batch_size: '%batch_size%'

  LogHandle:
    class: chains.log_handle.LogHandle
    arguments: ~

chains:
  - RabbitMqConsumer
  - LogHandle
  - ExampleApp