services:
  ExampleApp:
    class: processor.ExampleApp
    arguments: ~

  RabbitmqConsumer:
    class: chains.rabbitmq_consumer.RabbitmqConsumer
    arguments:
      uri: '%queue_consumer_uri%'
      queue: '%queue_consumer_name%'

  LogHandle:
    class: chains.log_handle.LogHandle
    arguments: ~

  RabbitmqProducer:
    class: chains.rabbitmq_consumer.RabbitmqConsumer
    arguments:
      uri: '%queue_producer_uri%'
      exchange: '%exchange_producer_name%'
      routing_key: '%routing_key_name%'

chains:
  - RabbitmqConsumer
  - LogHandle
  - ExampleApp
  - RabbitmqProducer