parameters:

  queue_consumer_uri: ['amqp://username:password@host:5672/']
  queue_consumer_name: 'ExampleQueue'
  batch_size: 100
  queue_consumer_uri: ['amqp://username:password@host:5672/']
  queue_consumer_name: 'ExampleExchange'